Refs #19 - NIC setup functions in mce-install.sh, prior to firstboot

diff --git a/src/Core/meta/firstboot_core b/src/Core/meta/firstboot_core
--- a/src/Core/meta/firstboot_core
+++ b/src/Core/meta/firstboot_core
@@ -18,20 +18,22 @@ done
 ###########################################################
 ###########################################################
 
-Nic_Config # setup initial nic config
-Configure_Network_Options # determine ip & int/ext if
-Configure_Network_Files # write /etc/network/interfaces /etc/hosts
-ifup -a || :
-TimeUpdate
-Configure_NTP_Server
-# Do not create and config under ubiquity.
-if ! grep ubiquity /proc/cmdline ; then
-	Create_And_Config_Core # create the core device in the database
-	Configure_Network_Database # write the network settings to the database
-	/usr/pluto/bin/Network_Setup.sh # setup all networking related services
-fi
-Configure_SSH_Server
-Configure_SSH_Client
+# These are done in mce-install.sh currently or setup fails.
+#
+#Nic_Config # setup initial nic config
+#Configure_Network_Options # determine ip & int/ext if
+#Configure_Network_Files # write /etc/network/interfaces /etc/hosts
+#ifup -a || :
+#TimeUpdate
+#Configure_NTP_Server
+## Do not create and config under ubiquity.
+#if ! grep ubiquity /proc/cmdline ; then
+#	Create_And_Config_Core # create the core device in the database
+#	Configure_Network_Database # write the network settings to the database
+#	/usr/pluto/bin/Network_Setup.sh # setup all networking related services
+#fi
+#Configure_SSH_Server
+#Configure_SSH_Client
 
 ###########################################################
 ###########################################################
